### ISSUE TITLE
AggregateException for parameter page in Wikipedia feature

### ISSUE THREAD

**Issue by dsdude123** [dsdude123/StarBot#20]
`
fail: commands[0]
      Command     Discord.Commands.CommandException: Error occurred executing "wiki" for [REDACTED} in [REDACTED]. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
      Parameter name: page
         at MediawikiSharp_API.Mediawiki.GetPageSections(String page, Boolean getImagesAndMatchToSections)
         at StarBot.Services.WikipediaService.<GetWikipediaPage>d__2.MoveNext()
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
         at StarBot.Modules.LookupModule.wikipedia(String topic)
         --- End of inner exception stack trace ---
`

**Comment by dsdude123** [comment]
Bug is the result of Wikipedia or Wikipedia.NET returning a single null result when query term is not found. Additionally, discovered a suggestion field which will be implemented as part of this fix to deal with misspellings.
